### ISSUE TITLE
Unable To Access the Index of Repository Issue

### ISSUE THREAD

**Issue by guid1984** [cloudfoundry/r-buildpack#13]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version ->  6.34.1+bbdf81482.2018-01-17
CF CLI -> 6.23.0

What version of the buildpack you are using?
r-buildpack-v1.1.1

If you were attempting to accomplish a task, what was it you were attempting to do?
trying to download packages from local jfrog artifactory, via r.yml please refer to my r.yml file
````
 ---
packages:
  - cran_mirror:  http://sres.web.xxx.com/artifactory/cran-remote-2/
    num_threads: 2
    packages:
      - name: stringr
      - name: jsonlite
      - name: vars 
````
Below is my manifest.yml
```

---
applications:
- name: metrics-discovery
  disk_qouta: 1GB
  memory: 1GB
  buildpack: r_buildpack
  random-route: false
  stack: cflinuxfs3
  health-check-type: port
  command: R -f start.R
  services: []
  env:
    CRAN_MIRROR: https://sres.web.xxx.com/artifactory/cran-remote-2/
    HTTP_PROXY: http://www-proxy.web.xxx.com:31060
    HTTPS_PROXY: https://www-proxy.web.xxx.com:31060
    CRAN_TRUSTED_HOST: sres.web.xxx.com
    PIP_TRUSTED_HOST: sres.web.xxx.com
```
Below is my start.R

```
library(stringr)
library(jsonlite)
library(vars)
library(plumber)
pr <- plumb("controller.R")
pr$run(host="0.0.0.0",port=8080)

```

What did you expect to happen?
app successfully pushed to PCF and the mentioned packages in r.yml gets deployed

What was the actual behavior?
cannot open URL 'http://sres.web.xxx.com/artifactory/cran-remote-2/src/contrib/PACKAGES'
 unable to access index for repository
```

2020-04-06T17:00:50.042+05:30 [APP/PROC/WEB/0] [OUT] > library(vars)
2020-04-06T17:00:50.043+05:30 [APP/PROC/WEB/0] [ERR] Error in library(vars) : there is no package called ‘vars’
2020-04-06T17:00:50.043+05:30 [APP/PROC/WEB/0] [ERR] Execution halted
2020-04-06T17:00:50.084+05:30 [APP/PROC/WEB/0] [OUT] Exit status 1
```

Please confirm where necessary:
* [Y ] I have included a log output
* [Y ] My log includes an error message
* [Y ] I have included steps for reproduction
